site_name: Digitize Guide
theme:
  name: material
  palette:
    scheme: slate
    primary: yellow
nav:
  - Getting Started: 'index.md'
  - 'Step 0.md'
  - 'Step 1.md'
  - 'Step 2.md'
  - 'Step 3.md'
  - 'Step 4.md'
  - 'Gotchas.md'
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
